### ISSUE TITLE
[Fundamentals - NFT primitives] NFT types

### ISSUE THREAD

**Issue by ipapandinas** [capsule-corp-ternoa/ternoa-doc#26]
### Todo

- [ ] Basic NFT
- [ ] Secret NFT
- [ ] Capsules
- [ ] Soulbound

### References

- [TIP 100: Basic NFT](https://github.com/capsule-corp-ternoa/ternoa-proposals/blob/main/TIPs/tip-100-Basic-NFT.md)
- [TIP 510: Secret NFT](https://github.com/capsule-corp-ternoa/ternoa-proposals/blob/main/TIPs/tip-510-Secret-nft.md)
- [TIP 104: Soulbound Token](https://github.com/capsule-corp-ternoa/ternoa-proposals/blob/main/TIPs/tip-104-Soulbound-Token.md)
- [Confluence: Basic NFT](https://ternoa.atlassian.net/wiki/spaces/PRODUCT/pages/289505287/Basic+NFT)
- [Confluence: Soulbound Token](https://ternoa.atlassian.net/wiki/spaces/PRODUCT/pages/296419466/SBT+SoulBound+Token+Journal+Summary)
- [Confluence: Secret NFT](https://ternoa.atlassian.net/wiki/spaces/PRODUCT/pages/303923342/Secret+NFT)
- [Confluence: Capsule NFT](https://ternoa.atlassian.net/wiki/spaces/PRODUCT/pages/251232257/Capsule+NFT)

**Comment by Balianos** [comment]
@M2613 need help on that ?
