### ISSUE TITLE
Epic: Ternoa Fundamentals > Ternoa Wiki

### ISSUE THREAD

**Issue by ipapandinas** [capsule-corp-ternoa/ternoa-doc#30]
### Description

This section introduces our blockchain and infrastructure to people who are new to Ternoa.
The aim is to describe things without getting too much deep into developers notions.

**Target**: Everybody, from new employees to anyone in the community.
Some technicals web3 prerequisites are a must since we are directly talking about NFTs.

### Todo

- [ ] #21
- [x] #24
- [ ] #25
- [x] #29

**Comment by ipapandinas** [comment]
Reopening this one too @M2613, #21 #25 #29 are not completed

**Comment by Balianos** [comment]
I'm checking the Renaming in the docs for texts and links
